# Environment configuration
settings:
  docker:
    requirements: requirements.txt
    environment:
      WANDB_DISABLED: "true"

# Step parameters
steps:
  data_ingestion:
    dataset_name: "imdb"
    cluster_name: "data-ingestion-cluster"
    n_workers: 3
    worker_cpu: 1
    worker_memory: 1024
    partition_size: 100
    scheduler_options: {"dashboard_address": ":8787"}
    subset_size: 1.0
    train_size: 0.7
    test_size: 0.1
    eval_size: 0.2
    random_state: 42 