tracking:
  auth:
    enabled: true
    username: slmops
    password: j6rXZAkyS}MOeYha
  ingress:
    enabled: true
    hostname: mlflow.lmorbits.com
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "5000m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "800"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "800"
    tls: true
  resources:
    limits:
      memory: "6Gi"
      cpu: "4"
    requests:
      memory: "4Gi"
      cpu: "2"
  extraEnvVars:
    - name: GUNICORN_CMD_ARGS
      value: "--timeout 600 --workers 4"
minio:
  enabled: false


externalGCS:
  bucket: "slmops-dev-ml-artifacts"
  googleCloudProject: "slmops-dev"
  useCredentialsInSecret: true
  existingSecret: "gcs-credentials"
  existingSecretKey: "credentials.json"
  serveArtifacts: true

