# http://zenml-server.zenml.svc.cluster.local
zenml:
  deploymentType: kubernetes
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /
    host: zenml.lmorbits.com
    path: /
    tls:
      enabled: true
      secretName: zenml-tls